apiVersion: twingate.com/v1beta
kind: TwingateResource
metadata:
  name: grafana-jwt-resource
  namespace: default
spec:
  type: WebApp
  name: "Demo · Grafana (JWT)"
  address: grafana.monitoring.svc.cluster.local
  alias: "grafana-jwt.octolet.int"
  gatewayRef:
    name: twop-gateway
    namespace: twingate
  downstream:
    port: 80
  upstream:
    port: 80
  requestHeaderRewrites:
    - name: "X-JWT-Assertion"
      value: "{{jwt}}"
