apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: admin
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.octolet.int"
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 3000
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: homepage-config-base
              mountPath: /app/config
            - name: homepage-config
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: homepage-config
              mountPath: /app/config/kubernetes.yaml
              subPath: kubernetes.yaml
            - name: homepage-config
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: homepage-config
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: homepage-config
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: homepage-config
              mountPath: /app/config/docker.yaml
              subPath: docker.yaml
            - name: logs
              mountPath: /app/config/logs
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: homepage-config-base
          emptyDir: {}
        - name: homepage-config
          configMap:
            name: homepage-config
        - name: logs
          emptyDir: {}
