apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: admin
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      initContainers:
        - name: copy-config
          image: busybox:latest
          command: ["sh", "-c", "cp /config-source/* /app/config/"]
          volumeMounts:
            - name: homepage-config-source
              mountPath: /config-source
            - name: homepage-config
              mountPath: /app/config
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.octolet.int"
          volumeMounts:
            - name: homepage-config
              mountPath: /app/config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: homepage-config-source
          configMap:
            name: homepage-config
        - name: homepage-config
          emptyDir: {}
