apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: blinkstick-controller-viewer
  labels:
    app: blinkstick-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: blinkstick-controller-viewer
subjects:
  - kind: ServiceAccount
    name: blinkstick-controller
    namespace: blinkstick
