apiVersion: v1
kind: ConfigMap
metadata:
  name: blinkstick-controller-config
  namespace: blinkstick
data:
  MQTT_BROKER: "mosquitto.blinkstick.svc.cluster.local"
  PROMETHEUS_URL: "http://prometheus-stack-kube-prom-prometheus.monitoring:9090"
  DEFAULT_MODE: "status"
  STATUS_POLL_INTERVAL: "15"
  LOG_LEVEL: "INFO"
