apiVersion: v1
kind: ServiceAccount
metadata:
  name: blinkstick-controller
  namespace: blinkstick
  labels:
    app: blinkstick-controller
    octolet/layer: hardware
    octolet/component: blinkstick
