apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshd
  namespace: default
  labels:
    app: sshd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshd
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
        - name: sshd
          image: alpine:latest
          command: ["sh", "/scripts/setup.sh"]
          ports:
            - containerPort: 2222
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
          startupProbe:
            tcpSocket:
              port: 2222
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 3
          readinessProbe:
            tcpSocket:
              port: 2222
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 2222
            periodSeconds: 10
          volumeMounts:
            - name: ca-key
              mountPath: /etc/ssh/ca_key
              subPath: ssh-privatekey
              readOnly: true
            - name: scripts
              mountPath: /scripts/setup.sh
              subPath: setup.sh
            - name: scripts
              mountPath: /scripts/sshd_config
              subPath: sshd_config
      volumes:
        - name: ca-key
          secret:
            secretName: twingate-ssh-ca
            defaultMode: 0400
        - name: scripts
          configMap:
            name: sshd-config
