apiVersion: v1
kind: Service
metadata:
  name: sshd
  namespace: default
  labels:
    app: sshd
  annotations:
    resource.twingate.com: "true"
    resource.twingate.com/type: "SSH"
    resource.twingate.com/name: "Demo · SSH Server"
    resource.twingate.com/gatewayName: "twop-gateway"
    resource.twingate.com/gatewayNamespace: "twingate"
    resource.twingate.com/alias: "ssh.octolet.int"
spec:
  selector:
    app: sshd
  ports:
    - name: ssh
      port: 22
      targetPort: 2222
      protocol: TCP
