apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate-operator
  namespace: argocd
spec:
  project: octolet
  sources:
    - repoURL: ghcr.io/twingate/helmcharts
      chart: twingate-operator
      targetRevision: "2.0.2"
      helm:
        releaseName: twop
        valueFiles:
          - $values/apps/networking/twingate/values.yaml
    - repoURL: https://github.com/graybern/octolet
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: twingate
  ignoreDifferences:
    - group: twingate.com
      kind: TwingateConnector
      jsonPointers:
        - /spec/id
        - /status
    - group: twingate.com
      kind: TwingateResource
      jsonPointers:
        - /spec/id
        - /status
    - group: twingate.com
      kind: TwingateGateway
      jsonPointers:
        - /spec/id
        - /status
    - group: twingate.com
      kind: TwingateCertificateAuthority
      jsonPointers:
        - /spec/id
        - /status
    - group: twingate.com
      kind: TwingateResourceAccess
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
