apiVersion: v1
kind: Service
metadata:
  name: twingate-connector-metrics
  namespace: twingate
  labels:
    octolet/component: twingate-connector
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    octolet/component: twingate-connector
