apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: twop-connector-1
  namespace: twingate
spec:
  name: prem-tejon-octolet-twop-1
  logAnalytics: true
  logLevel: 3
  hasStatusNotificationsEnabled: true
  image:
    repository: twingate/connector
    tag: latest
  podLabels:
    octolet/component: twingate-connector
  containerExtra:
    env:
      - name: TWINGATE_METRICS_PORT
        value: "9999"
    ports:
      - containerPort: 9999
        name: metrics
        protocol: TCP
---
apiVersion: twingate.com/v1beta
kind: TwingateConnector
metadata:
  name: twop-connector-2
  namespace: twingate
spec:
  name: prem-tejon-octolet-twop-2
  logAnalytics: true
  logLevel: 3
  hasStatusNotificationsEnabled: true
  image:
    repository: twingate/connector
    tag: latest
  podLabels:
    octolet/component: twingate-connector
  containerExtra:
    env:
      - name: TWINGATE_METRICS_PORT
        value: "9999"
    ports:
      - containerPort: 9999
        name: metrics
        protocol: TCP
