apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - application.yaml
  - connectors.yaml
  - connector-service.yaml
  - connector-servicemonitor.yaml
  - access.yaml
  - clusterrolebinding.yaml
