twingateOperator:
  existingAPIKeySecret:
    name: twingate-operator-api-key
    key: TWINGATE_API_KEY
  network: "gbernard"
  remoteNetworkId: "UmVtb3RlTmV0d29yazozMjE1OTU="
  logFormat: "json"
  defaultResourceTags:
    managed-by: twingate-operator
    environment: octolet

image:
  repository: twingate/kubernetes-operator
  pullPolicy: IfNotPresent

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  seccompProfile:
    type: RuntimeDefault

gateway:
  enabled: true
  twingate:
    network: "gbernard"
  twingateOperator:
    gateway:
      enabled: true
      certificateAuthority:
        name: "octolet-gateway-ca"
    kubernetesResource:
      enabled: true
      name: "Infra · K8s API"
      alias: "api-k8s.octolet.int"
  kubernetes:
    enabled: true
  ssh:
    enabled: true
    gateway:
      username: "ubuntu"
    ca:
      manual:
        existingSecret: "twingate-ssh-ca"
  webApp:
    enabled: true
  tls:
    existingSecret: "twop-gateway-tls"
    autoGenerated:
      enabled: false
    dnsNames:
      - "app.int"
      - "grafana.octolet.int"
      - "ssh.octolet.int"
      - "headlamp.octolet.int"
      - "*.default.svc.cluster.local"
  metrics:
    serviceMonitor:
      enabled: true
      interval: 30s
    grafanaDashboard:
      enabled: true
      labels:
        grafana_dashboard: "1"
    prometheusRule:
      enabled: true
